version: '3.4'

services:
  dockerservicedemo:
    image: ${DOCKER_REGISTRY}dockerservicedemo
    build:
      context: .
      dockerfile: DockerServiceDemo/Dockerfile
    ports:
      - 5000:80
  proxy:
    image: nginx:latest
    volumes:
      - ./DockerServiceDemo/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80