networks:
    postgresql-bridge:
        driver: bridge
    rabbitmq-bridge:
        driver: bridge
    redis-bridge:
        driver: bridge
    neo4j-bridge:
        driver: bridge
    api-gateway-bridge:
        driver: bridge

volumes:
    postgresql-db: 

services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.10.7-management
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5673:5673
            - 15672:15672
        networks: 
            - rabbitmq-bridge
    
    neo4j:
        container_name: neo4j
        image: neo4j:latest
        ports:
          - 7474:7474
          - 7687:7687
        environment:
          - NEO4J_AUTH=neo4j/P@ssword
          - NEO4J_apoc_export_file_enabled=true
          - NEO4J_apoc_import_file_enabled=true
          - NEO4J_apoc_import_file_use__neo4j__config=true
          - NEO4J_PLUGINS=["apoc"]
        volumes:
          - ./neo4j_db/data:/data
          - ./neo4j_db/logs:/logs
          - ./neo4j_db/import:/var/lib/neo4j/import
          - ./neo4j_db/plugins:/plugins
        networks:
            - neo4j-bridge

    postgresql:
        container_name: postgresql
        image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "123"
        ports:
          - "5432:5432"
        networks:
            - postgresql-bridge
        volumes:
            - postgresql-db:/var/lib/postgresql/data

    redis:
        image: redis:latest
        ports:
          - "6379:6379"
        networks:
            - redis-bridge

    user-microservice:
        container_name: user-microservice
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        image: ${DOCKER_REGISTRY}user-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/User/NetSpace.User.PublicApi/Dockerfile-dev
        ports:
            - 2000:8080
        networks:
            - redis-bridge
            - postgresql-bridge
            - rabbitmq-bridge
            - api-gateway-bridge
        depends_on: 
            - postgresql
            - redis
            - rabbitmq
    
    identity-microservice:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        image: ${DOCKER_REGISTRY}identity-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/Identity/NetSpace.Identity.Api/Dockerfile-dev
        ports:
            - 2001:8080    
        networks:
            - redis-bridge
            - postgresql-bridge
            - rabbitmq-bridge
            - api-gateway-bridge
        depends_on: 
            - postgresql
            - redis
            - rabbitmq

    friendship-microservice:
        container_name: friendship-microservice
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        image: ${DOCKER_REGISTRY}friendship-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/Friendship/NetSpace.Friendship.Api/Dockerfile-dev
        ports:
            - 2002:8080
        networks:
            - redis-bridge
            - neo4j-bridge
            - rabbitmq-bridge
            - api-gateway-bridge
        depends_on: 
            - neo4j
            - redis
            - rabbitmq

    email-microservice:
        container_name: email-microservice
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        image: ${DOCKER_REGISTRY}email-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/EmailSender/NetSpace.EmailSender.Api/Dockerfile-dev
        ports:
            - 2003:8080
        networks:
            - rabbitmq-bridge

    community-microservice:
        container_name: community-microservice
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        image: ${DOCKER_REGISTRY}community-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/Community/NetSpace.Community.Api/Dockerfile-dev
        ports:
            - 2004:8080
        networks:
            - redis-bridge
            - postgresql-bridge
            - rabbitmq-bridge
            - api-gateway-bridge
        depends_on: 
            - postgresql
            - redis
            - rabbitmq

    api-gateway:
        container_name: api-gateway
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        image: ${DOCKER_REGISTRY}api-gateway-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/NetSpace.ApiGateway/Dockerfile-dev
        ports:
            - 2005:8080
        networks:
            - api-gateway-bridge
