services:
    rabbitmq:
        image: rabbitmq:3.10.7-management
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5673:5673
            - 15672:15672
    

    neo4j:
        container_name: neo4j
        image: neo4j:latest
        ports:
          - 7474:7474
          - 7687:7687
        environment:
          - NEO4J_AUTH=neo4j/P@ssword
          - NEO4J_apoc_export_file_enabled=true
          - NEO4J_apoc_import_file_enabled=true
          - NEO4J_apoc_import_file_use__neo4j__config=true
          - NEO4J_PLUGINS=["apoc"]
        volumes:
          - ./neo4j_db/data:/data
          - ./neo4j_db/logs:/logs
          - ./neo4j_db/import:/var/lib/neo4j/import
          - ./neo4j_db/plugins:/plugins

    postgresql:
        image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - "5432:5432"
    redis:
        image: redis:latest
        ports:
          - "6379:6379"

    user-microservice:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Release
        image: ${DOCKER_REGISTRY}user-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/User/NetSpace.User.PublicApi/Dockerfile
        ports:
            - 2000:8080
    
    identity-microservice:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Release
        image: ${DOCKER_REGISTRY}identity-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/Identity/NetSpace.Identity.PublicApi/Dockerfile
        ports:
            - 2001:8080    

    friendship-microservice:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Release
        image: ${DOCKER_REGISTRY}friendship-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/Friendship/NetSpace.Friendship.PublicApi/Dockerfile
        ports:
            - 2002:8080

    email-microservice:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Release
        image: ${DOCKER_REGISTRY}email-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/EmailSender/NetSpace.EmailSender.PublicApi/Dockerfile
        ports:
            - 2003:8080
            
    community-microservice:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Release
        image: ${DOCKER_REGISTRY}community-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/Community/NetSpace.Community.PublicApi/Dockerfile
        ports:
            - 2004:8080

    api-gateway:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Release
        image: ${DOCKER_REGISTRY}api-gateway-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/NetSpace.ApiGateway/Dockerfile
        ports:
            - 2005:8080
