version: '3.8'

services:
    user-microservice:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        image: ${DOCKER_REGISTRY}user-microservice
        build: 
            context: .
            dockerfile: ./src/Backend/Microservices/User/NetSpace.User.PublicApi/Dockerfile
        ports:
            - 2000:5502

    rabbitmq:
        image: rabbitmq:3.10.7-management
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5673:5673
            - 15672:15672
    neo4j:
        container_name: neo4j
        image: neo4j:latest
        ports:
          - 7474:7474
          - 7687:7687
        environment:
          - NEO4J_AUTH=neo4j/P@ssword
          - NEO4J_apoc_export_file_enabled=true
          - NEO4J_apoc_import_file_enabled=true
          - NEO4J_apoc_import_file_use__neo4j__config=true
          - NEO4J_PLUGINS=["apoc"]
        volumes:
          - ./neo4j_db/data:/data
          - ./neo4j_db/logs:/logs
          - ./neo4j_db/import:/var/lib/neo4j/import
          - ./neo4j_db/plugins:/plugins
    postgresql:
        image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - "5432:5432"
    redis:
        image: redis:latest
        ports:
          - "6379:6379"
